"""Константы для ошибок"""

RECIPE_NOT_FOUND_ERROR = 'Рецепта не существует'
RECIPE_ALREADY_EXISTS_ERROR = 'Рецепта уже существует!'
RECIPE_ALREADY_ADDED_ERROR = 'Рецепт уже добавлен в избранное!'
SUBSCRIPTION_ALREADY_EXISTS_ERROR = 'Вы уже подписаны на этого пользователя!'
SUBSCRIPTION_SELF_ERROR = 'Нельзя подписаться на самого себя'
SUBSCRIPTION_NOT_FOUND_ERROR = 'Подписка не найдена'
RECIPE_NOT_IN_FAVORITES_ERROR = 'Рецепт не найден в избранном пользователя'
RECIPE_NOT_IN_SHOPPING_CART_ERROR = 'Рецепт не найден в корзине'
AUTHOR_NOT_FOUND_ERROR = 'Автор не найден'
RECIPE_ALREADY_ADDED_IN_CARD = 'Рецепт уже добавлен в корзину!'
AUTHENTION_ERROR = 'Для создания рецепта необходимо залогиниться'
INGREDIENTS_NOT_IN_RECIPE = 'В рецепте отсутсвуют ингредиенты'
TAGS_NOT_IN_RECIPE = 'У рецепта должен быть тег.'
IMAGE_NOT_IN_RECIPE = 'У рецепта должна быть картинка'
NOT_ID_INGREDIENTS = 'Требуется id ингредиента'
INGREDIENT_ALREADY_ADDED = 'Повторяющиеся ингредиенты в рецепте'
INGREDIENT_WITH_THIS_ID_NOT_EXISTS = 'Ингредиента с таким id не существует'
TAG_ALREADY_ADDED = 'Повторяющиеся теги в рецепте'
TAG_WITH_THIS_ID_NOT_EXISTS = 'Тега с этим id не существует'
INGREDIENT_AMOUNT_ERROR = 'Количество ингредиента должно быть больше/равно 1'
INGREDIENT_AMOUNT_FORMAT_ERROR = 'Количество ингредиента должно быть числj'
COOKING_TIME_ERROR = 'Время приготовления не может быть меньше 1 минуты'
INVALID_CHARTERS_IN_USRNAME = 'Не правельные символы в username.'
