name: Main foodgram workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Добавляем возможность запуска по запросу
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions

      - name: Print project tree
        run: tree .
